// Regenerates src/abi.ts from the compiled contracts (run `forge build` in contracts/ first).
//   node scripts/gen-abi.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const out = (name) => JSON.parse(readFileSync(new URL(`../../../contracts/out/${name}.sol/${name}.json`, import.meta.url))).abi;
const body = [
  '// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.',
  `export const factoryAbi = ${JSON.stringify(out('PlinthFactory'), null, 1)} as const;`,
  `export const vaultAbi = ${JSON.stringify(out('PlinthVault'), null, 1)} as const;`,
  '',
].join('\n\n');
writeFileSync(new URL('../src/abi.ts', import.meta.url), body);
console.log('wrote src/abi.ts');
