[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "../data" }]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "solady/=lib/solady/src/",
]

[rpc_endpoints]
bsc = "${BSC_ARCHIVE_RPC_URL}"

[fmt]
line_length = 110
