// Copied from packages/keeper/src/abi.ts by scripts/sync-agent.sh. Edit the original.
// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.

export const factoryAbi = [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "owner_",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "usdt_",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "oracle_",
    "type": "address",
    "internalType": "contract IResilientOracle"
   },
   {
    "name": "markets_",
    "type": "tuple[]",
    "internalType": "struct Market[]",
    "components": [
     {
      "name": "kind",
      "type": "uint8",
      "internalType": "enum MarketKind"
     },
     {
      "name": "target",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "receipt",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "debt",
      "type": "address",
      "internalType": "address"
     }
    ]
   },
   {
    "name": "gate_",
    "type": "tuple",
    "internalType": "struct GateLimits",
    "components": [
     {
      "name": "minCashMultiple",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxUtilization",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxPegDeviation",
      "type": "uint64",
      "internalType": "uint64"
     }
    ]
   },
   {
    "name": "maxFloorRate_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "term_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "keeper_",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "venusBlocksPerYear_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "minTrade_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "minOpen_",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "CHANGE_DELAY",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BAND",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_CAP",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_SLIPPAGE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "acceptKeeper",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "acceptOwnership",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "addStock",
  "inputs": [
   {
    "name": "s",
    "type": "tuple",
    "internalType": "struct StockConfig",
    "components": [
     {
      "name": "token",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "pool",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "router",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "pancake",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "venusPriced",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "twapWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "cap",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "band",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxSlippage",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "fastWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "maxTrade",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "maxVault",
      "type": "uint128",
      "internalType": "uint128"
     }
    ]
   }
  ],
  "outputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "applyCap",
  "inputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "gate",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct GateLimits",
    "components": [
     {
      "name": "minCashMultiple",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxUtilization",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxPegDeviation",
      "type": "uint64",
      "internalType": "uint64"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "implementation",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "keeper",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "liveCap",
  "inputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "market",
  "inputs": [
   {
    "name": "i",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct Market",
    "components": [
     {
      "name": "kind",
      "type": "uint8",
      "internalType": "enum MarketKind"
     },
     {
      "name": "target",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "receipt",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "debt",
      "type": "address",
      "internalType": "address"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "marketCount",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "marketEnabled",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "maxFloorRate",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "minOpen",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "minTrade",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "open",
  "inputs": [
   {
    "name": "stockId",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "promiseBps",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "amount",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "vault",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "oracle",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "contract IResilientOracle"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingCap",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingCapAt",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingKeeper",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingKeeperAt",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingOwner",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "proposeKeeper",
  "inputs": [
   {
    "name": "k",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "removeKeeper",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "renounceOwnership",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setCap",
  "inputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "cap_",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMarketEnabled",
  "inputs": [
   {
    "name": "i",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "on",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMinOpen",
  "inputs": [
   {
    "name": "m",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setMinTrade",
  "inputs": [
   {
    "name": "m",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setStockEnabled",
  "inputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "on",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setVenusBlocksPerYear",
  "inputs": [
   {
    "name": "b",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "stock",
  "inputs": [
   {
    "name": "id",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct StockConfig",
    "components": [
     {
      "name": "token",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "pool",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "router",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "pancake",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "venusPriced",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "twapWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "cap",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "band",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxSlippage",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "fastWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "maxTrade",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "maxVault",
      "type": "uint128",
      "internalType": "uint128"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "stockCount",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "stockEnabled",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "term",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "transferOwnership",
  "inputs": [
   {
    "name": "newOwner",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "usdt",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "vaultCount",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "vaults",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "vaultsOf",
  "inputs": [
   {
    "name": "saver",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address[]",
    "internalType": "address[]"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "venusBlocksPerYear",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "event",
  "name": "CapProposed",
  "inputs": [
   {
    "name": "stockId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "cap",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "at",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "CapSet",
  "inputs": [
   {
    "name": "stockId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "cap",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "KeeperProposed",
  "inputs": [
   {
    "name": "keeper",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "at",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "KeeperSet",
  "inputs": [
   {
    "name": "keeper",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "MarketEnabled",
  "inputs": [
   {
    "name": "marketIndex",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "enabled",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "MinOpenSet",
  "inputs": [
   {
    "name": "minOpen",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "MinTradeSet",
  "inputs": [
   {
    "name": "minTrade",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferStarted",
  "inputs": [
   {
    "name": "previousOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OwnershipTransferred",
  "inputs": [
   {
    "name": "previousOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "newOwner",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "StockAdded",
  "inputs": [
   {
    "name": "stockId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "token",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "StockEnabled",
  "inputs": [
   {
    "name": "stockId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "enabled",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "VaultOpened",
  "inputs": [
   {
    "name": "saver",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "vault",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "stockId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "promiseBps",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "VenusBlocksPerYearSet",
  "inputs": [
   {
    "name": "blocks",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "BadAmount",
  "inputs": []
 },
 {
  "type": "error",
  "name": "BadConfig",
  "inputs": []
 },
 {
  "type": "error",
  "name": "BadPromise",
  "inputs": []
 },
 {
  "type": "error",
  "name": "FailedDeployment",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InsufficientBalance",
  "inputs": [
   {
    "name": "balance",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "needed",
    "type": "uint256",
    "internalType": "uint256"
   }
  ]
 },
 {
  "type": "error",
  "name": "OwnableInvalidOwner",
  "inputs": [
   {
    "name": "owner",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "OwnableUnauthorizedAccount",
  "inputs": [
   {
    "name": "account",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "SafeERC20FailedOperation",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "StockOff",
  "inputs": []
 },
 {
  "type": "error",
  "name": "TooEarly",
  "inputs": []
 }
] as const;

export const vaultAbi = [
 {
  "type": "constructor",
  "inputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "IDLE_GRACE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "RAISE_INTERVAL",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "RAISE_STEP",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "beginExit",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "cancelExit",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "cap",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "capAtOpen",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "deposit",
  "inputs": [
   {
    "name": "amount",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "deposited",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "effectiveMultiplier",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "excess",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "exiting",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "factory",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "contract IPlinthFactory"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "idleSince",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "impaired",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "initialize",
  "inputs": [
   {
    "name": "saver_",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "stockId_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "stock_",
    "type": "tuple",
    "internalType": "struct StockConfig",
    "components": [
     {
      "name": "token",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "pool",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "router",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "pancake",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "venusPriced",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "twapWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "cap",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "band",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxSlippage",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "fastWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "maxTrade",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "maxVault",
      "type": "uint128",
      "internalType": "uint128"
     }
    ]
   },
   {
    "name": "promiseBps_",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "term_",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "lastRaiseAt",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "marketIndex",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "maturity",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "moveSafeLeg",
  "inputs": [
   {
    "name": "to",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "multiplier",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "promiseBps",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "promised",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pullOutIfUnhealthy",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "rateSeen",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "rebalance",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "roll",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "saver",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "setMultiplier",
  "inputs": [
   {
    "name": "m",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "status",
  "inputs": [],
  "outputs": [
   {
    "name": "s",
    "type": "tuple",
    "internalType": "struct PlinthVault.Status",
    "components": [
     {
      "name": "total",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "stockUsd",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "safeUsd",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "price",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "slowPrice",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "fastPrice",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "floor",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "target",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "breakDistance",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "floorRate",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "multiplier",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "cap",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "promised",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "deposited",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maturity",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "marketIndex",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "gateCode",
      "type": "uint8",
      "internalType": "uint8"
     },
     {
      "name": "nextRaiseAt",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "idleSince",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "excess",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "impaired",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "exiting",
      "type": "bool",
      "internalType": "bool"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "stock",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct StockConfig",
    "components": [
     {
      "name": "token",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "pool",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "router",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "pancake",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "venusPriced",
      "type": "bool",
      "internalType": "bool"
     },
     {
      "name": "twapWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "cap",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "band",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxSlippage",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "fastWindow",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "maxTrade",
      "type": "uint128",
      "internalType": "uint128"
     },
     {
      "name": "maxVault",
      "type": "uint128",
      "internalType": "uint128"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "stockId",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "sync",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "term",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "usdt",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "withdraw",
  "inputs": [
   {
    "name": "share",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "withdrawInKind",
  "inputs": [
   {
    "name": "share",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "includeStock",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "event",
  "name": "Deposited",
  "inputs": [
   {
    "name": "from",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "promised",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ExitCancelled",
  "inputs": [],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ExitStarted",
  "inputs": [],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "HeldAside",
  "inputs": [
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "excess",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Impaired",
  "inputs": [
   {
    "name": "marketIndex",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "gateCode",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Initialized",
  "inputs": [
   {
    "name": "version",
    "type": "uint64",
    "indexed": false,
    "internalType": "uint64"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "MovedSafeLeg",
  "inputs": [
   {
    "name": "from",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "to",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "MultiplierSet",
  "inputs": [
   {
    "name": "by",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "multiplier",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PulledOut",
  "inputs": [
   {
    "name": "marketIndex",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "gateCode",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Rebalanced",
  "inputs": [
   {
    "name": "reason",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum FloorMath.Reason"
   },
   {
    "name": "deltaUsd",
    "type": "int256",
    "indexed": false,
    "internalType": "int256"
   },
   {
    "name": "price",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "total",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "floor",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "target",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "multiplier",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Rolled",
  "inputs": [
   {
    "name": "maturity",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "promised",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "SupplyRefused",
  "inputs": [
   {
    "name": "marketIndex",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Traded",
  "inputs": [
   {
    "name": "buy",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   },
   {
    "name": "usdtAmount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "tokens",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Withdrawn",
  "inputs": [
   {
    "name": "share",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "usdtOut",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "promisedLeft",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "WithdrawnInKind",
  "inputs": [
   {
    "name": "share",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "stockOut",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "receiptOut",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "usdtOut",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "AboveCap",
  "inputs": []
 },
 {
  "type": "error",
  "name": "BadShare",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidInitialization",
  "inputs": []
 },
 {
  "type": "error",
  "name": "MarketDisabled",
  "inputs": []
 },
 {
  "type": "error",
  "name": "MarketUnhealthy",
  "inputs": [
   {
    "name": "code",
    "type": "uint8",
    "internalType": "uint8"
   }
  ]
 },
 {
  "type": "error",
  "name": "NotInitializing",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotKeeper",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotMatured",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotSaver",
  "inputs": []
 },
 {
  "type": "error",
  "name": "OverVaultLimit",
  "inputs": []
 },
 {
  "type": "error",
  "name": "RaiseTooBig",
  "inputs": []
 },
 {
  "type": "error",
  "name": "RaiseTooSoon",
  "inputs": []
 },
 {
  "type": "error",
  "name": "ReentrancyGuardReentrantCall",
  "inputs": []
 },
 {
  "type": "error",
  "name": "SafeERC20FailedOperation",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "UseStagedExit",
  "inputs": []
 }
] as const;

